# -*- coding: utf-8 -*-
"""202401100700123_B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fV-IwjHWCKR-7B7aAArTWqmE2Abqvwyd
"""

import random
import time
import threading

def monitor_temperature():
    """Function to generate random temperature and provide alerts."""
    while not stop_event.is_set():
        temperature = round(random.uniform(0, 50), 2)  # Generate random temperature
        if temperature < 10:
            print(f"Alert: Temperature {temperature}°C is too low! Increase heating.")
        elif 10 <= temperature <= 35:
            print(f"Temperature {temperature}°C is normal.")
        else:
            print(f"Alert: Temperature {temperature}°C is too high! Cooling required.")

        time.sleep(2)  # Check temperature every 2 seconds

# Event to control stopping the loop
stop_event = threading.Event()

# Start monitoring in a separate thread
thread = threading.Thread(target=monitor_temperature)
thread.start()

# User input loop to quit monitoring
print("Temperature monitoring started. Press 'q' and Enter to exit.\n")

while True:
    user_input = input().strip().lower()
    if user_input == 'q':
        stop_event.set()  # Signal the thread to stop
        thread.join()  # Wait for the thread to exit
        print("\nExiting temperature monitoring...")
        break