# -*- coding: utf-8 -*-
"""Copy of CaseStudy5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkXkOaTTfEnd-uHtKTtsxwlYQFFzUdEH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load CSV file
file_path = "data sheet csv.csv"  # Update path if needed
df = pd.read_csv(file_path)

# Clean column names
df.columns = df.columns.str.strip().str.lower()

# Convert marks to percentage (max marks = 15)
df['percentage'] = (df['marks'] / 15) * 100

# Categorize students
above_75 = df[df['percentage'] > 75]
between_60_75 = df[(df['percentage'] >= 60) & (df['percentage'] <= 75)]
below_60 = df[df['percentage'] < 60]

# Print categorized students
print("Students with > 75%:\n", above_75[['name', 'percentage']], "\n")
print("Students between 60% and 75%:\n", between_60_75[['name', 'percentage']], "\n")
print("Students with < 60%:\n", below_60[['name', 'percentage']], "\n")

# Plot histogram
plt.figure(figsize=(8, 5))
plt.hist(
    [above_75['percentage'], between_60_75['percentage'], below_60['percentage']],
    bins=np.arange(0, 101, 5),
    color=['blue', 'green', 'red'],        # Add one color per category
    edgecolor='black',
    label=['>75%', '60–75%', '<60%']
)

plt.xlabel("Percentage")
plt.ylabel("Number of Students")
plt.title("Histogram plot")
plt.legend()
plt.show()

# Plot scatter plot
plt.figure(figsize=(10, 5))
plt.scatter(df['name'], df['percentage'], color='blue', edgecolors='black')
plt.xticks(rotation=90)
plt.xlabel("Students")
plt.ylabel("Percentage")
plt.title("Scatter plot")
plt.tight_layout()
plt.show()