# -*- coding: utf-8 -*-
"""LED_CONTROL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOgX005iRmL-NWwxVIKaGZpAUBejvlxA
"""

import tkinter as tk

root = tk.Tk()
root.title("LED Control")

led_status = True
brightness = 50

canvas = tk.Canvas(root, width=200, height=200, bg="black")
canvas.pack()

led = canvas.create_oval(50, 50, 150, 150, fill="green")

label = tk.Label(root, text=f"Brightness: {brightness}%", font=("Arial", 12))
label.pack()

def update_led():
    global led_status, brightness
    if led_status:
        color = f"#{int(255 * brightness / 100):02x}{int(255 * brightness / 100):02x}00"
    else:
        color = "black"
    canvas.itemconfig(led, fill=color)
    label.config(text=f"Brightness: {brightness}%")

def key_pressed(event):
    global brightness, led_status
    if event.keysym == "Up" and brightness < 100:
        brightness += 10
    elif event.keysym == "Down" and brightness > 0:
        brightness -= 10
    elif event.keysym == "space":
        led_status = not led_status
    update_led()

root.bind("<Up>", key_pressed)
root.bind("<Down>", key_pressed)
root.bind("<space>", key_pressed)

update_led()
root.mainloop()