# -*- coding: utf-8 -*-
"""ToDoList.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zIrEP7aM4DaDu9mW07xkVCQornfUyd2z
"""

# Simple To-Do List Program

todo_list = []

def add_task():
    task = input("Enter the task: ")
    todo_list.append({"task": task, "completed": False})
    print("Task added successfully!\n")

def view_tasks():
    if not todo_list:
        print("No tasks in the list.\n")
        return
    print("\nTo-Do List:")
    for index, task in enumerate(todo_list, start=1):
        status = " Completed" if task["completed"] else " Not Completed"
        print(f"{index}. {task['task']} - {status}")
    print()

def delete_task():
    view_tasks()
    try:
        task_num = int(input("Enter the task number to delete: "))
        if 1 <= task_num <= len(todo_list):
            removed = todo_list.pop(task_num - 1)
            print(f"Task '{removed['task']}' deleted successfully!\n")
        else:
            print("Invalid task number.\n")
    except ValueError:
        print("Please enter a valid number.\n")

def mark_task_complete():
    view_tasks()
    try:
        task_num = int(input("Enter the task number to mark as complete: "))
        if 1 <= task_num <= len(todo_list):
            todo_list[task_num - 1]["completed"] = True
            print("Task marked as completed!\n")
        else:
            print("Invalid task number.\n")
    except ValueError:
        print("Please enter a valid number.\n")

def main():
    while True:
        print("------ To-Do List Menu ------")
        print("1. Add Task")
        print("2. View Tasks")
        print("3. Delete Task")
        print("4. Mark Task as Complete")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            add_task()
        elif choice == '2':
            view_tasks()
        elif choice == '3':
            delete_task()
        elif choice == '4':
            mark_task_complete()
        elif choice == '5':
            print("Exiting To-Do List. Have a great day!")
            break
        else:
            print("Invalid choice! Please enter a number between 1 and 5.\n")

if __name__ == "__main__":
    main()